version: '3.1'

services:

  db:
    image: mariadb:10.7.4-focal
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: mariadbapp
      MARIADB_USER: admin
      MARIADB_PASSWORD: admin123
      TZ: America/Sao_Paulo

    volumes:
      - ./db:/var/lib/mysql
    ports:
      - 3306:3306
